### ISSUE TITLE
A more descriptive message than 'Oops'

### ISSUE THREAD

**Issue by jpaulin** [ekonstantinidis/npm-click#31]
It's wonderful tool! Exactly what I would imagine using for a lot!

Can the feedback be more descriptive about when there's something wrong with the package.json 
that was submitted for analysis? 

Like this kind of visualizations a lot. Effortless, but I'm currently stuck in mindless loop of trying to figure out what is wrong with a ca. 60 item list. 
:-)

Cheers,
J

**Comment by ekonstantinidis** [comment]
Hi there! Sorry for the late reply but I didn't work on this project for a while(or ages)! I went through and rewrote the app from scratch with React v15, Redux & Immutable. This bug is now fixed! When you copy the contents of your file, you will get an alert if something is wrong - specifying where the mistake is.
